# Permalinks
permalink:        pretty

# Setup
title:            Ulvgard 
tagline:          
url:              www.ulvgard.se
paginate:         2
baseurl:          /
author:
  name:           Tobias Ulvgård 
  url:            www.ulvgard.se
  email:          foo@bar.com
  repository:	  ulvgard.github.io

# Custom vars
version:          1.0.0
github:		      ulvgard

# menu 
pages_list:       
    Posts: /posts
    Archive: /archive
    Feed: /atom.xml

gems: [jekyll-paginate]
